name: webpack workflow

on:
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint "**/*.{js,ts,jsx,tsx}" --max-warnings=0

  webpack-build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Webpack build
        run: npm run build

      - name: Check bundle size
        run: npx size-limit

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: webpack-dist
          path: dist

      - name: Upload bundle analysis report
        uses: actions/upload-artifact@v3
        with:
          name: bundle-report
          path: bundle-report.html
